export const products = [
  {
    id: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    storage: "256GB",
    category: "New",
    condition: "Factory sealed",
    price: 138000,
    originalPrice: 156000,
    stock: 18,
    color: "Natural Titanium",
    battery: "100%",
    warranty: "12 months manufacturer",
    processor: "A17 Pro",
    ram: "8GB",
    camera: "48MP Pro",
    source: "Nairobi-ready authorized import stock",
    arrival: "Same-day Nairobi dispatch",
    inspection: ["Serial verified", "Carrier unlocked", "Sealed box", "eTIMS invoice ready"],
    image:
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "samsung-s24-ultra",
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    storage: "512GB",
    category: "Refurbished",
    condition: "Grade A+",
    price: 92000,
    originalPrice: 125000,
    stock: 9,
    color: "Titanium Gray",
    battery: "94%",
    warranty: "12 months PhoneVault",
    processor: "Snapdragon 8 Gen 3",
    ram: "12GB",
    camera: "200MP Quad",
    source: "Ex-UK Grade A verified batch",
    arrival: "Same-day Nairobi dispatch",
    inspection: ["Battery tested", "S Pen tested", "Display calibrated", "IMEI clean"],
    image:
      "https://images.unsplash.com/photo-1704895723473-86dd4ab18f0f?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "pixel-9-pro",
    name: "Google Pixel 9 Pro",
    brand: "Google",
    storage: "256GB",
    category: "Imported",
    condition: "Open box",
    price: 110000,
    originalPrice: 122000,
    stock: 6,
    color: "Obsidian",
    battery: "100%",
    warranty: "12 months PhoneVault",
    processor: "Tensor G4",
    ram: "16GB",
    camera: "50MP AI",
    source: "Verified import partner",
    arrival: "Arrives in 3-5 days",
    inspection: ["Safaricom bands checked", "Bootloader clean", "Original accessories", "Import costs disclosed"],
    image:
      "https://images.unsplash.com/photo-1662947995683-ec516c2e2f57?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "iphone-14-pro",
    name: "iPhone 14 Pro",
    brand: "Apple",
    storage: "128GB",
    category: "Used",
    condition: "Excellent",
    price: 63000,
    originalPrice: 76000,
    stock: 12,
    color: "Deep Purple",
    battery: "88%",
    warranty: "6 months PhoneVault",
    processor: "A16 Bionic",
    ram: "6GB",
    camera: "48MP Pro",
    source: "Clean ex-UK trade-in program",
    arrival: "Ships tomorrow",
    inspection: ["Face ID tested", "Camera tested", "Battery certified", "No iCloud lock"],
    image:
      "https://images.unsplash.com/photo-1663499482523-1c0c1bae4ce1?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "oneplus-12",
    name: "OnePlus 12",
    brand: "OnePlus",
    storage: "256GB",
    category: "New",
    condition: "Factory sealed",
    price: 81000,
    originalPrice: 83500,
    stock: 21,
    color: "Flowy Emerald",
    battery: "100%",
    warranty: "12 months manufacturer",
    processor: "Snapdragon 8 Gen 3",
    ram: "16GB",
    camera: "Hasselblad 50MP",
    source: "Kenya retail import partner",
    arrival: "Ships today",
    inspection: ["Sealed box", "Charger included", "Carrier unlocked", "eTIMS invoice ready"],
    image:
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "xiaomi-14-ultra",
    name: "Xiaomi 14 Ultra",
    brand: "Xiaomi",
    storage: "512GB",
    category: "Imported",
    condition: "Grade A",
    price: 105000,
    originalPrice: 126000,
    stock: 5,
    color: "Black Vegan Leather",
    battery: "96%",
    warranty: "9 months PhoneVault",
    processor: "Snapdragon 8 Gen 3",
    ram: "16GB",
    camera: "Leica 50MP Quad",
    source: "Hong Kong verified import stock",
    arrival: "Arrives in 4-6 days",
    inspection: ["Bands disclosed", "Google services ready", "Camera tested", "Import duty shown"],
    image:
      "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?auto=format&fit=crop&w=900&q=80",
  },
];

export const categories = ["All", "New", "Refurbished", "Used", "Imported"];

export const faqs = [
  ["Are these phones authentic?", "Yes. Every unit is serial checked, IMEI screened, carrier-unlock verified, and sold with a visible inspection record."],
  ["What does transparent pricing mean?", "Each product shows list price, savings, warranty, battery health, source, shipping expectation, and any import considerations before checkout."],
  ["Can I compare before buying?", "Yes. Add up to three phones to the comparison tray and compare battery, warranty, stock, source, and key specs side by side."],
  ["What happens after checkout?", "This prototype prepares a cart and quote flow. A production build would connect payment, order tracking, inventory sync, and CRM notifications."],
];
